# .github/workflows/ci.yml

name: CI Pipeline

# Controls when the workflow will run
on:
  # Triggers the workflow on push events for ALL branches
  push:
    branches:
      - '**'
  # Triggers the workflow on pull request events targeting ANY branch
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. Sets up Node.js and enables pnpm caching for faster installs
      - name: Setup Node.js and pnpm
        uses: actions/setup-node@v4
        with:
          node-version: 20 # Or your preferred Node.js LTS version
          cache: 'pnpm'

      # 3. Installs project dependencies
      - name: Install Dependencies
        run: pnpm install

      # 4. Runs the linter across the entire monorepo
      - name: Run Linter
        run: pnpm lint

      # 5. Builds all apps and packages to ensure there are no compilation or type errors
      - name: Build All Packages
        run: pnpm build

      # 6. Runs all unit and integration tests
      - name: Run Tests
        run: pnpm test
